# Pandas Tutorial
Pandas is an open-source library that is built on top of NumPy library. It is a Python package that offers various data structures and operations for manipulating numerical data and time series. It is mainly popular for importing and analyzing data much easier. Pandas is fast and it has high-performance & productivity for users. 

# Advantages 
1. Fast and efficient for manipulating and analyzing data.
2. Data from different file objects can be loaded.
3. Easy handling of missing data (represented as NaN) in floating point as well as non-floating point data
4. Size mutability: columns can be inserted and deleted from DataFrame and higher dimensional objects
5. Data set merging and joining.
6. Flexible reshaping and pivoting of data sets
7. Provides time-series functionality.
8. Powerful group by functionality for performing split-apply-combine operations on data sets.

Pandas generally provide two data structure for manipulating data, They are:

1. Series
2. DataFrame

In [1]:
import pandas as pd
import numpy as np

In [2]:
# lets create series
# creating empty series
ser = pd.Series()
print(ser)
arr = np.array(['A', 'B', 'C', 'D', 'F'])
series = pd.Series(arr)
print(series)

Series([], dtype: float64)
0    A
1    B
2    C
3    D
4    F
dtype: object


/home/ankit/.local/lib/python3.6/site-packages/ipykernel_launcher.py:3: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  This is separate from the ipykernel package so we can avoid doing imports until


In [13]:
# lets create dataframe
df = pd.DataFrame()
lst = np.array(["ankit", "suwal", "abhay", "sonu", "bhoomi"])
daff = pd.DataFrame(lst)
daff

0
0   ankit
1   suwal
2   abhay
3    sonu
4  bhoomi

# Why panda use for datascience?
Panda is build on Numpy library which means that a lot of structures of NumPy are used or replicated in Pandas.
The data produced by Pandas is often used as input for plotting functions of Matplotlib, statistical analysis in 
SciPy, machine learning algorithm in Scikit-learn.

In [3]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4), index=['Row1','Row2','Row3','Row4','Row5'], columns=['C1','C2','C3','C4'])
df

C1  C2  C3  C4
Row1   0   1   2   3
Row2   4   5   6   7
Row3   8   9  10  11
Row4  12  13  14  15
Row5  16  17  18  19

In [20]:
# you can also create csv file using inbuilt function to_csv
df.to_csv('test1.csv')

In [4]:
df.loc['Row1']
type(df.loc['Row1'])

pandas.core.series.Series

In [14]:
# LHS you give rows and RHS you give colums
# just to remember: in python index start with 0 and in R index start with 1
print(df.iloc[0:2,0:2])
# if I have more than one column its type is Dataframe
print(type(df.iloc[0:2,0:2]))
print(type(df.iloc[0:1,0:1]))
# or if I have zero column than type is series
print(df.iloc[0:2,0])
print(type(df.iloc[0:2,0]))

      C1  C2
Row1   0   1
Row2   4   5
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
Row1    0
Row2    4
Name: C1, dtype: int64
<class 'pandas.core.series.Series'>


In [17]:
# can dataframe converted into array: YES, lets see
print(df.iloc[:, :].values)
df.iloc[:,:].values.shape

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


(5, 4)

In [20]:
# check null value
df.isnull()

C1     C2     C3     C4
Row1  False  False  False  False
Row2  False  False  False  False
Row3  False  False  False  False
Row4  False  False  False  False
Row5  False  False  False  False

In [21]:
df.isnull().sum()

C1    0
C2    0
C3    0
C4    0
dtype: int64

In [ ]:
df.isnull().