# If you want to understand about any lib please put cursor and tab 

In [10]:
# install numpy in conda env by: conda install -c anaconda numpy
# importing python lib numpy
import numpy as np

In [11]:
my_list = [1,2,3,4]

In [12]:
arr = np.array(my_list)

In [13]:
print(my_list, arr, type(my_list), type(arr))

[1, 2, 3, 4] [1 2 3 4] <class 'list'> <class 'numpy.ndarray'>


In [14]:
# Creating a rank 1 Array
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [15]:
# Creating a rank 2 Array
arr2 = np.array([[1, 2, 3],
                [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr.shape

(4,)

# Multinested array

In [23]:

list1 = [1,2,3,4]
list2 = [5,6,7,8]
list3 = [11,22,33,44]
multi_arr = np.array([list1, list2, list3])
print(multi_arr, multi_arr.shape)
# how will you identify 1d, 2d or 3d array is ?
# [values]: 1D array, [[values]]: 2D array, [[[values]]]: 3D array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 22 33 44]] (3, 4)


In [28]:
#reshaping the array using reshape
# while u are reshaping the array, count of values must be same
print(multi_arr.reshape(4,3))
print(multi_arr.reshape(1,12), multi_arr.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 11]
 [22 33 44]]
[[ 1  2  3  4  5  6  7  8 11 22 33 44]] (3, 4)


In [26]:
#you can check the shape its still in 2D: ie: [[]]
multi_arr.shape

(3, 4)

# Indexing

In [35]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
print(arr)
arr1 = arr.reshape(2,5)
arr1

[1 2 3 4 5 6 7 8 9 0]


array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [36]:
# If you want to retrive any value just remember the index of value like(index always start from zero :P)
arr[3]

4

In [37]:
multi_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 22, 33, 44]])

In [41]:
#print last two colums
print(multi_arr[:,2:])
print("==============================")
# print 2nd and 3rd row and 2nd and 3rd column
print(multi_arr[1:, 1:3])

[[ 3  4]
 [ 7  8]
 [33 44]]
[[ 6  7]
 [22 33]]


In [45]:
# some inbuilt functions like: arange, linespace
arr = np.arange(0,10)
print(arr)
# you will get in between numbers
np.linspace(0,1)

[0 1 2 3 4 5 6 7 8 9]


array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [47]:
# copy function and broadcasting 
print(arr)
arr[:4] =111
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[111 111 111 111   4   5   6   7   8   9]


In [50]:
arr11 = arr.copy()
print(arr, arr11)
arr11[8:] = 222
print(arr11)

[111 111 111 111   4   5   6   7   8   9] [111 111 111 111   4   5   6   7   8   9]
[111 111 111 111   4   5   6   7 222 222]


In [56]:
#some usefull conditions for EDA(Exploratry Data Analysis)
value=4
arr[arr>8]
print(arr*2)
print(arr/2)
print(arr<8)

[222 222 222 222   8  10  12  14  16  18]
[55.5 55.5 55.5 55.5  2.   2.5  3.   3.5  4.   4.5]
[False False False False  True  True  True  True False False]
